name: Snyk SAST 
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  Snyk-SAST:
    runs-on: ubuntu-latest
    environment: gsa-integration-test-2
    continue-on-error: true
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v4
      - name: install snyk
        run: npm install -g snyk
      - name: Snyk CLI Version
        run: snyk --version
      - name: Configure environment
        run: snyk config environment SNYK-GOV-01
      - name: Authenticate with Snyk SaaS
        run: snyk auth --org="${{ secrets.SNYK_ORG_ID }}" --client-id="${{ secrets.SNYK_CLIENT_ID }}" --client-secret="${{ secrets.SNYK_CLIENT_SECRET }}"
      - name: SAST 
        if: always()
        run: snyk code test --org="${{ secrets.SNYK_ORG_ID }}" 

